# Generated by Django 4.2.6 on 2023-10-30 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='src/img/models')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('asset_number', models.IntegerField()),
                ('serial_number', models.CharField(max_length=255)),
                ('drive_serialnumber', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('avaiable', 'Avaiable'), ('home office', 'Home office'), ('asigned', 'Asigned'), ('travel', 'Travel'), ('disposed', 'Disposed')], default='avaiable', max_length=50)),
                ('location', models.CharField(choices=[('control de gestion', 'Control de Gestion'), ('presidencia', 'Presidencia'), ('office', 'Office'), ('planta baja', 'Planta Baja'), ('panol', 'Panol'), ('planta', 'Planta'), ('aceptacion', 'Aceptacion')], default='office', max_length=50)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('laptop', 'Laptop')], default='desktop', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.devicemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
